### ISSUE TITLE
Missing AWS credentials should give a friendlier error message

### ISSUE THREAD

**Issue by jkinkead** [allenai/datastore#21]
When we get a `AmazonS3Exception: Access Denied` error in the datastore, we should wrap & re-throw with a friendlier message.

Specifically, we should include a link to the [getting started guide](https://github.com/allenai/wiki/wiki/Getting-Started#setting-up-your-developer-environment), calling out the step where you set up your AWS credentials.

**Comment by dirkgr** [comment]
Oh, it didn't auto-close this :-(
