### ISSUE TITLE
Exclude datastore-cli as a publish artifact

### ISSUE THREAD

**Issue by schmmd** [allenai/datastore#6]
Do we want to exclude this and not publish to Maven Central?

**Comment by dirkgr** [comment]
Why? I guess you'd never consume it as a library. Maybe you want to write a CLI that wraps this CLI or something? It's a remote possibility, to be sure, but it doesn't get into anyone's way the way it is.

**Comment by dirkgr** [comment]
I think we talked about this and decided not to do it?

**Comment by schmmd** [comment]
Yes.
